import type { Kanji } from './types'

/**
 * Seed curriculum: 12 fully-authored N5 kanji (readings, example words, and
 * hand-authored stroke order) followed by 8 "Tier 2" kanji with readings and
 * examples but no stroke order yet.
 *
 * Stroke paths are simplified straight/curved segments in a shared 0-100
 * viewBox, matching the app's flat thick-round-cap aesthetic (not
 * calligraphic realism) — not glyph-accurate KanjiVG data. Real stroke-order
 * data is a backend-phase concern (see the design handoff's Assets section).
 */
export const KANJI_DATA: Kanji[] = [
  {
    day: 1,
    character: '一',
    meaning: 'один',
    kunReading: { kana: 'ひと(つ)', romaji: 'hito(tsu)' },
    onReading: { kana: 'イチ', romaji: 'ichi' },
    jlptLevel: 'N5',
    strokeCount: 1,
    exampleWords: [
      { word: '一つ', kana: 'ひとつ', romaji: 'hitotsu', translation: 'один (предмет)' },
      { word: '一月', kana: 'いちがつ', romaji: 'ichigatsu', translation: 'январь' },
      { word: '一人', kana: 'ひとり', romaji: 'hitori', translation: 'один человек' },
    ],
    strokes: [
      { d: 'M15 50 L85 50', start: { x: 15, y: 50 }, instruction: 'слева направо' },
    ],
    writingNote: 'Одна черта. Веди слева направо, ровно и спокойно.',
  },
  {
    day: 2,
    character: '二',
    meaning: 'два',
    kunReading: { kana: 'ふた(つ)', romaji: 'futa(tsu)' },
    onReading: { kana: 'ニ', romaji: 'ni' },
    jlptLevel: 'N5',
    strokeCount: 2,
    exampleWords: [
      { word: '二つ', kana: 'ふたつ', romaji: 'futatsu', translation: 'два (предмета)' },
      { word: '二月', kana: 'にがつ', romaji: 'nigatsu', translation: 'февраль' },
      { word: '二人', kana: 'ふたり', romaji: 'futari', translation: 'два человека' },
    ],
    strokes: [
      { d: 'M15 35 L85 35', start: { x: 15, y: 35 }, instruction: 'верхняя черта' },
      { d: 'M15 65 L85 65', start: { x: 15, y: 65 }, instruction: 'нижняя черта' },
    ],
    writingNote: 'Две черты. Сначала верхняя, потом нижняя — обе слева направо.',
  },
  {
    day: 3,
    character: '三',
    meaning: 'три',
    kunReading: { kana: 'み(っつ)', romaji: 'mi(ttsu)' },
    onReading: { kana: 'サン', romaji: 'san' },
    jlptLevel: 'N5',
    strokeCount: 3,
    exampleWords: [
      { word: '三つ', kana: 'みっつ', romaji: 'mittsu', translation: 'три (предмета)' },
      { word: '三月', kana: 'さんがつ', romaji: 'sangatsu', translation: 'март' },
      { word: '三人', kana: 'さんにん', romaji: 'sannin', translation: 'три человека' },
    ],
    strokes: [
      { d: 'M15 25 L85 25', start: { x: 15, y: 25 }, instruction: 'верхняя черта' },
      { d: 'M15 50 L85 50', start: { x: 15, y: 50 }, instruction: 'средняя черта' },
      { d: 'M15 75 L85 75', start: { x: 15, y: 75 }, instruction: 'нижняя черта' },
    ],
    writingNote: 'Три черты подряд, сверху вниз: верхняя, средняя, нижняя. Каждая — слева направо.',
  },
  {
    day: 4,
    character: '十',
    meaning: 'десять',
    kunReading: { kana: 'とお', romaji: 'too' },
    onReading: { kana: 'ジュウ', romaji: 'juu' },
    jlptLevel: 'N5',
    strokeCount: 2,
    exampleWords: [
      { word: '十日', kana: 'とおか', romaji: 'tooka', translation: 'десятое число' },
      { word: '十月', kana: 'じゅうがつ', romaji: 'juugatsu', translation: 'октябрь' },
      { word: '五十', kana: 'ごじゅう', romaji: 'gojuu', translation: 'пятьдесят' },
    ],
    strokes: [
      { d: 'M15 50 L85 50', start: { x: 15, y: 50 }, instruction: 'горизонтальная, слева направо' },
      { d: 'M50 15 L50 85', start: { x: 50, y: 15 }, instruction: 'вертикальная, сверху вниз' },
    ],
    writingNote: 'Две черты. Сначала горизонтальная слева направо, потом вертикальная сверху вниз через середину.',
  },
  {
    day: 5,
    character: '人',
    meaning: 'человек',
    kunReading: { kana: 'ひと', romaji: 'hito' },
    onReading: { kana: 'ジン', romaji: 'jin' },
    jlptLevel: 'N5',
    strokeCount: 2,
    exampleWords: [
      { word: '日本人', kana: 'にほんじん', romaji: 'nihonjin', translation: 'японец' },
      { word: '外人', kana: 'がいじん', romaji: 'gaijin', translation: 'иностранец' },
      { word: '大人', kana: 'おとな', romaji: 'otona', translation: 'взрослый' },
    ],
    strokes: [
      { d: 'M55 20 L20 85', start: { x: 55, y: 20 }, instruction: 'сверху вниз-влево' },
      { d: 'M50 35 L82 85', start: { x: 50, y: 35 }, instruction: 'сверху вниз-вправо' },
    ],
    writingNote: 'Две черты, как ноги идущего человека. Сначала длинная влево-вниз, потом короче — вправо-вниз.',
  },
  {
    day: 6,
    character: '大',
    meaning: 'большой',
    kunReading: { kana: 'おお(きい)', romaji: 'oo(kii)' },
    onReading: { kana: 'ダイ', romaji: 'dai' },
    jlptLevel: 'N5',
    strokeCount: 3,
    exampleWords: [
      { word: '大きい', kana: 'おおきい', romaji: 'ookii', translation: 'большой' },
      { word: '大学', kana: 'だいがく', romaji: 'daigaku', translation: 'университет' },
      { word: '大好き', kana: 'だいすき', romaji: 'daisuki', translation: 'очень нравится' },
    ],
    strokes: [
      { d: 'M20 40 L80 40', start: { x: 20, y: 40 }, instruction: 'горизонтальная черта' },
      { d: 'M50 15 L20 85', start: { x: 50, y: 15 }, instruction: 'черта влево-вниз' },
      { d: 'M55 25 L80 85', start: { x: 55, y: 25 }, instruction: 'черта вправо-вниз' },
    ],
    writingNote: 'Три черты. Сначала горизонтальная, потом от центра — влево-вниз и вправо-вниз, как раскинутые руки.',
  },
  {
    day: 7,
    character: '木',
    meaning: 'дерево',
    kunReading: { kana: 'き', romaji: 'ki' },
    onReading: { kana: 'モク', romaji: 'moku' },
    jlptLevel: 'N5',
    strokeCount: 4,
    exampleWords: [
      { word: '木曜日', kana: 'もくようび', romaji: 'mokuyoubi', translation: 'четверг' },
      { word: '木村', kana: 'きむら', romaji: 'kimura', translation: 'Кимура (фамилия)' },
      { word: '大木', kana: 'たいぼく', romaji: 'taiboku', translation: 'большое дерево' },
    ],
    strokes: [
      { d: 'M20 35 L80 35', start: { x: 20, y: 35 }, instruction: 'горизонтальная черта' },
      { d: 'M50 10 L50 90', start: { x: 50, y: 10 }, instruction: 'вертикальная, сверху вниз' },
      { d: 'M50 50 L20 90', start: { x: 50, y: 50 }, instruction: 'черта влево-вниз' },
      { d: 'M52 55 L80 90', start: { x: 52, y: 55 }, instruction: 'черта вправо-вниз' },
    ],
    writingNote: 'Четыре черты: горизонтальная, вертикальная через неё, затем две черты-ветви вниз — влево и вправо.',
  },
  {
    day: 8,
    character: '川',
    meaning: 'река',
    kunReading: { kana: 'かわ', romaji: 'kawa' },
    onReading: { kana: 'セン', romaji: 'sen' },
    jlptLevel: 'N5',
    strokeCount: 3,
    exampleWords: [
      { word: '川', kana: 'かわ', romaji: 'kawa', translation: 'река' },
      { word: '小川', kana: 'おがわ', romaji: 'ogawa', translation: 'ручей' },
      { word: '河川', kana: 'かせん', romaji: 'kasen', translation: 'реки (обобщённо)' },
    ],
    strokes: [
      { d: 'M25 20 L20 80', start: { x: 25, y: 20 }, instruction: 'левая черта' },
      { d: 'M50 15 L50 85', start: { x: 50, y: 15 }, instruction: 'средняя черта' },
      { d: 'M75 20 L80 80', start: { x: 75, y: 20 }, instruction: 'правая черта' },
    ],
    writingNote: 'Три вертикальные черты одна за другой, слева направо. Как берега и течение реки.',
  },
  {
    day: 9,
    character: '火',
    meaning: 'огонь',
    kunReading: { kana: 'ひ', romaji: 'hi' },
    onReading: { kana: 'カ', romaji: 'ka' },
    jlptLevel: 'N5',
    strokeCount: 4,
    exampleWords: [
      { word: '火曜日', kana: 'かようび', romaji: 'kayoubi', translation: 'вторник' },
      { word: '花火', kana: 'はなび', romaji: 'hanabi', translation: 'фейерверк' },
      { word: '火山', kana: 'かざん', romaji: 'kazan', translation: 'вулкан' },
    ],
    strokes: [
      { d: 'M45 15 L35 30', start: { x: 45, y: 15 }, instruction: 'короткая черта, вверху слева' },
      { d: 'M55 15 L65 28', start: { x: 55, y: 15 }, instruction: 'короткая черта, вверху справа' },
      { d: 'M55 35 L20 85', start: { x: 55, y: 35 }, instruction: 'длинная черта влево-вниз' },
      { d: 'M50 45 L85 85', start: { x: 50, y: 45 }, instruction: 'длинная черта вправо-вниз' },
    ],
    writingNote: 'Четыре черты. Сначала две короткие вверху, потом две длинные — влево-вниз и вправо-вниз.',
  },
  {
    day: 10,
    character: '日',
    meaning: 'солнце, день',
    kunReading: { kana: 'ひ', romaji: 'hi' },
    onReading: { kana: 'ニチ', romaji: 'nichi' },
    jlptLevel: 'N5',
    strokeCount: 4,
    exampleWords: [
      { word: '日曜日', kana: 'にちようび', romaji: 'nichiyoubi', translation: 'воскресенье' },
      { word: '毎日', kana: 'まいにち', romaji: 'mainichi', translation: 'каждый день' },
      { word: '日本', kana: 'にほん', romaji: 'nihon', translation: 'Япония' },
    ],
    strokes: [
      { d: 'M25 20 L25 80', start: { x: 25, y: 20 }, instruction: 'левая вертикальная черта' },
      { d: 'M25 20 L75 20 L75 80', start: { x: 25, y: 20 }, instruction: 'верх и правая сторона одной чертой' },
      { d: 'M25 50 L75 50', start: { x: 25, y: 50 }, instruction: 'средняя горизонтальная черта' },
      { d: 'M25 80 L75 80', start: { x: 25, y: 80 }, instruction: 'нижняя черта, закрывает' },
    ],
    writingNote: 'Четыре черты: левая сторона, затем верх и правая сторона одной чертой, потом средняя и нижняя линии.',
  },
  {
    day: 11,
    character: '月',
    meaning: 'луна, месяц',
    kunReading: { kana: 'つき', romaji: 'tsuki' },
    onReading: { kana: 'ゲツ', romaji: 'getsu' },
    jlptLevel: 'N5',
    strokeCount: 4,
    exampleWords: [
      { word: '月曜日', kana: 'げつようび', romaji: 'getsuyoubi', translation: 'понедельник' },
      { word: '今月', kana: 'こんげつ', romaji: 'kongetsu', translation: 'этот месяц' },
      { word: '一月', kana: 'いちがつ', romaji: 'ichigatsu', translation: 'январь' },
    ],
    strokes: [
      { d: 'M25 20 L25 80', start: { x: 25, y: 20 }, instruction: 'левая черта' },
      { d: 'M25 20 L75 20 L75 80 L25 80', start: { x: 25, y: 20 }, instruction: 'верх, право и низ одной чертой' },
      { d: 'M35 45 L65 45', start: { x: 35, y: 45 }, instruction: 'первая внутренняя черта' },
      { d: 'M35 62 L65 62', start: { x: 35, y: 62 }, instruction: 'вторая внутренняя черта' },
    ],
    writingNote: 'Четыре черты: левая сторона, затем верх, право и низ одной чертой, потом две черты внутри.',
  },
  {
    day: 12,
    character: '山',
    meaning: 'гора',
    kunReading: { kana: 'やま', romaji: 'yama' },
    onReading: { kana: 'サン', romaji: 'san' },
    jlptLevel: 'N5',
    strokeCount: 3,
    exampleWords: [
      { word: '火山', kana: 'かざん', romaji: 'kazan', translation: 'вулкан' },
      { word: '山道', kana: 'やまみち', romaji: 'yamamichi', translation: 'горная тропа' },
      { word: '富士山', kana: 'ふじさん', romaji: 'Fuji-san', translation: 'гора Фудзи' },
    ],
    strokes: [
      { d: 'M50 20 L50 72', start: { x: 50, y: 20 }, instruction: 'сверху вниз' },
      { d: 'M22 32 L22 80 L82 80', start: { x: 22, y: 32 }, instruction: 'вниз и вправо' },
      { d: 'M80 26 L80 80', start: { x: 80, y: 26 }, instruction: 'правая стена' },
    ],
    writingNote: 'Три черты. Сначала середина, потом левая стена с дном, в конце — правая. Обведи пальцем по серому.',
  },

  // Tier 2 — readings and examples authored, stroke order not yet done.
  {
    day: 13,
    character: '女',
    meaning: 'женщина',
    kunReading: { kana: 'おんな', romaji: 'onna' },
    onReading: { kana: 'ジョ', romaji: 'jo' },
    jlptLevel: 'N5',
    strokeCount: 3,
    exampleWords: [
      { word: '女の子', kana: 'おんなのこ', romaji: 'onna no ko', translation: 'девочка' },
      { word: '女性', kana: 'じょせい', romaji: 'josei', translation: 'женщина (офиц.)' },
      { word: '彼女', kana: 'かのじょ', romaji: 'kanojo', translation: 'она, девушка' },
    ],
  },
  {
    day: 14,
    character: '子',
    meaning: 'ребёнок',
    kunReading: { kana: 'こ', romaji: 'ko' },
    onReading: { kana: 'シ', romaji: 'shi' },
    jlptLevel: 'N5',
    strokeCount: 3,
    exampleWords: [
      { word: '子供', kana: 'こども', romaji: 'kodomo', translation: 'ребёнок, дети' },
      { word: '男の子', kana: 'おとこのこ', romaji: 'otoko no ko', translation: 'мальчик' },
      { word: '息子', kana: 'むすこ', romaji: 'musuko', translation: 'сын' },
    ],
  },
  {
    day: 15,
    character: '水',
    meaning: 'вода',
    kunReading: { kana: 'みず', romaji: 'mizu' },
    onReading: { kana: 'スイ', romaji: 'sui' },
    jlptLevel: 'N5',
    strokeCount: 4,
    exampleWords: [
      { word: '水曜日', kana: 'すいようび', romaji: 'suiyoubi', translation: 'среда' },
      { word: '水泳', kana: 'すいえい', romaji: 'suiei', translation: 'плавание' },
      { word: 'お水', kana: 'おみず', romaji: 'o-mizu', translation: 'вода (вежливо)' },
    ],
  },
  {
    day: 16,
    character: '土',
    meaning: 'земля',
    kunReading: { kana: 'つち', romaji: 'tsuchi' },
    onReading: { kana: 'ド', romaji: 'do' },
    jlptLevel: 'N5',
    strokeCount: 3,
    exampleWords: [
      { word: '土曜日', kana: 'どようび', romaji: 'doyoubi', translation: 'суббота' },
      { word: '土地', kana: 'とち', romaji: 'tochi', translation: 'земля, участок' },
    ],
  },
  {
    day: 17,
    character: '金',
    meaning: 'золото, деньги',
    kunReading: { kana: 'かね', romaji: 'kane' },
    onReading: { kana: 'キン', romaji: 'kin' },
    jlptLevel: 'N5',
    strokeCount: 8,
    exampleWords: [
      { word: 'お金', kana: 'おかね', romaji: 'o-kane', translation: 'деньги' },
      { word: '金曜日', kana: 'きんようび', romaji: "kin'youbi", translation: 'пятница' },
      { word: '金魚', kana: 'きんぎょ', romaji: 'kingyo', translation: 'золотая рыбка' },
    ],
  },
  {
    day: 18,
    character: '口',
    meaning: 'рот',
    kunReading: { kana: 'くち', romaji: 'kuchi' },
    onReading: { kana: 'コウ', romaji: 'kou' },
    jlptLevel: 'N5',
    strokeCount: 3,
    exampleWords: [
      { word: '入口', kana: 'いりぐち', romaji: 'iriguchi', translation: 'вход' },
      { word: '出口', kana: 'でぐち', romaji: 'deguchi', translation: 'выход' },
      { word: '人口', kana: 'じんこう', romaji: 'jinkou', translation: 'население' },
    ],
  },
  {
    day: 19,
    character: '中',
    meaning: 'середина, внутри',
    kunReading: { kana: 'なか', romaji: 'naka' },
    onReading: { kana: 'チュウ', romaji: 'chuu' },
    jlptLevel: 'N5',
    strokeCount: 4,
    exampleWords: [
      { word: '中国', kana: 'ちゅうごく', romaji: 'chuugoku', translation: 'Китай' },
      { word: '中心', kana: 'ちゅうしん', romaji: 'chuushin', translation: 'центр' },
      { word: '中学校', kana: 'ちゅうがっこう', romaji: 'chuugakkou', translation: 'средняя школа' },
    ],
  },
  {
    day: 20,
    character: '上',
    meaning: 'верх',
    kunReading: { kana: 'うえ', romaji: 'ue' },
    onReading: { kana: 'ジョウ', romaji: 'jou' },
    jlptLevel: 'N5',
    strokeCount: 3,
    exampleWords: [
      { word: '上手', kana: 'じょうず', romaji: 'jouzu', translation: 'умелый, искусный' },
      { word: '机の上', kana: 'つくえのうえ', romaji: 'tsukue no ue', translation: 'на столе' },
    ],
  },
]

export function getKanjiByDay(day: number): Kanji | undefined {
  return KANJI_DATA.find((k) => k.day === day)
}
