"""добавить meaning_suggested в kanji

Revision ID: 6b28124140cd
Revises: b1a64e275715
Create Date: 2026-08-06 08:56:33.367207
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6b28124140cd'
down_revision: Union[str, None] = 'b1a64e275715'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kanji', sa.Column('meaning_suggested', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kanji', 'meaning_suggested')
    # ### end Alembic commands ###
