"""создание таблиц kanji, devices, reviews

Revision ID: b1a64e275715
Revises: 
Create Date: 2026-08-06 08:48:51.519054
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'b1a64e275715'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('timezone', sa.String(length=64), server_default='UTC', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kanji',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character', sa.String(length=4), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('meaning', sa.Text(), nullable=True),
    sa.Column('meaning_en', sa.Text(), nullable=True),
    sa.Column('kun_reading_kana', sa.String(length=64), nullable=True),
    sa.Column('kun_reading_romaji', sa.String(length=64), nullable=True),
    sa.Column('on_reading_kana', sa.String(length=64), nullable=True),
    sa.Column('on_reading_romaji', sa.String(length=64), nullable=True),
    sa.Column('jlpt_level', sa.String(length=2), nullable=True),
    sa.Column('stroke_count', sa.Integer(), nullable=True),
    sa.Column('frequency', sa.Integer(), nullable=True),
    sa.Column('radical_number', sa.Integer(), nullable=True),
    sa.Column('writing_note', sa.Text(), nullable=True),
    sa.Column('example_words', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('strokes', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('is_published', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('needs_review', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('character'),
    sa.UniqueConstraint('order_index')
    )
    op.create_index('ix_kanji_jlpt_level', 'kanji', ['jlpt_level'], unique=False)
    op.create_index('ix_kanji_published_order', 'kanji', ['is_published', 'order_index'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('kanji_id', sa.Integer(), nullable=False),
    sa.Column('repetitions', sa.Integer(), server_default='0', nullable=False),
    sa.Column('interval_days', sa.Integer(), server_default='0', nullable=False),
    sa.Column('ease_factor', sa.Numeric(precision=4, scale=2), server_default='2.50', nullable=False),
    sa.Column('next_review_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('lapses', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_reviews', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['kanji_id'], ['kanji.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'kanji_id', name='uq_reviews_device_kanji')
    )
    op.create_index('ix_reviews_device_created', 'reviews', ['device_id', 'created_at'], unique=False)
    op.create_index('ix_reviews_device_next_review', 'reviews', ['device_id', 'next_review_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_reviews_device_next_review', table_name='reviews')
    op.drop_index('ix_reviews_device_created', table_name='reviews')
    op.drop_table('reviews')
    op.drop_index('ix_kanji_published_order', table_name='kanji')
    op.drop_index('ix_kanji_jlpt_level', table_name='kanji')
    op.drop_table('kanji')
    op.drop_table('devices')
    # ### end Alembic commands ###
